//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AugmentedReadingApp
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class ProjectionScreen
    {
        //
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.SettingsButton = new System.Windows.Forms.Button();
            this.HideCalibrationMarksButton = new System.Windows.Forms.Button();
            this.CapturedContentLabel = new System.Windows.Forms.Label();
            this.CapturedContentPanel = new System.Windows.Forms.Panel();
            this.ModeLabel = new System.Windows.Forms.Label();
            this.SyncHighlightImageButton = new System.Windows.Forms.Button();
            this.HighlightModeLabel = new System.Windows.Forms.Label();
            this.LeftPanel = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.RightPanelServiceLabel = new System.Windows.Forms.Label();
            this.RightPanelSearchingLabel = new System.Windows.Forms.Label();
            this.RightPanelTittleLabel = new System.Windows.Forms.Label();
            this.HighlightModeImageButton = new System.Windows.Forms.Button();
            this.WebSearcherImageButton = new System.Windows.Forms.Button();
            this.SynchronizerImageButton = new System.Windows.Forms.Button();
            this.XRightPanelImageButton = new System.Windows.Forms.Button();
            this.RightArrowImageButton = new System.Windows.Forms.Button();
            this.LeftArrowImageButton = new System.Windows.Forms.Button();
            this.HistoryImageButton = new System.Windows.Forms.Button();
            this.TurnOffImageButton = new System.Windows.Forms.Button();
            this.ContentImageButton = new System.Windows.Forms.Button();
            this.FiguresImageButton = new System.Windows.Forms.Button();
            this.CommentsImageButton = new System.Windows.Forms.Button();
            this.BookmarkImageButton = new System.Windows.Forms.Button();
            this.VideosImageButton = new System.Windows.Forms.Button();
            this.ImagesImageButton = new System.Windows.Forms.Button();
            this.TranslatorImageButton = new System.Windows.Forms.Button();
            this.DictionaryImageButton = new System.Windows.Forms.Button();
            this.EncyclopediaImageButton = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // SettingsButton
            // 
            this.SettingsButton.Location = new System.Drawing.Point(1010, 18);
            this.SettingsButton.Name = "SettingsButton";
            this.SettingsButton.Size = new System.Drawing.Size(102, 58);
            this.SettingsButton.TabIndex = 1;
            this.SettingsButton.Text = "Settings";
            this.SettingsButton.UseVisualStyleBackColor = true;
            // 
            // HideCalibrationMarksButton
            // 
            this.HideCalibrationMarksButton.Location = new System.Drawing.Point(1146, 644);
            this.HideCalibrationMarksButton.Name = "HideCalibrationMarksButton";
            this.HideCalibrationMarksButton.Size = new System.Drawing.Size(102, 56);
            this.HideCalibrationMarksButton.TabIndex = 3;
            this.HideCalibrationMarksButton.Text = "Hide calibration marks";
            this.HideCalibrationMarksButton.UseVisualStyleBackColor = true;
            // 
            // CapturedContentLabel
            // 
            this.CapturedContentLabel.AutoSize = true;
            this.CapturedContentLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CapturedContentLabel.Location = new System.Drawing.Point(522, 7);
            this.CapturedContentLabel.Name = "CapturedContentLabel";
            this.CapturedContentLabel.Size = new System.Drawing.Size(196, 29);
            this.CapturedContentLabel.TabIndex = 6;
            this.CapturedContentLabel.Text = "Captured content";
            // 
            // CapturedContentPanel
            // 
            this.CapturedContentPanel.BackColor = System.Drawing.Color.White;
            this.CapturedContentPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.CapturedContentPanel.Location = new System.Drawing.Point(445, 39);
            this.CapturedContentPanel.Name = "CapturedContentPanel";
            this.CapturedContentPanel.Size = new System.Drawing.Size(348, 39);
            this.CapturedContentPanel.TabIndex = 8;
            // 
            // ModeLabel
            // 
            this.ModeLabel.AutoSize = true;
            this.ModeLabel.Location = new System.Drawing.Point(554, 493);
            this.ModeLabel.Name = "ModeLabel";
            this.ModeLabel.Size = new System.Drawing.Size(114, 13);
            this.ModeLabel.TabIndex = 10;
            this.ModeLabel.Text = "Capture mode enabled";
            this.ModeLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // SyncHighlightImageButton
            // 
            this.SyncHighlightImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.SyncHighlightImageButton.FlatAppearance.BorderSize = 0;
            this.SyncHighlightImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.SyncHighlightImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.SyncHighlightImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.SyncHighlightImageButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SyncHighlightImageButton.Image = global::AugmentedReadingApp.Properties.Resources.SyncHighlightsButtonImage;
            this.SyncHighlightImageButton.Location = new System.Drawing.Point(670, 18);
            this.SyncHighlightImageButton.Name = "SyncHighlightImageButton";
            this.SyncHighlightImageButton.Size = new System.Drawing.Size(81, 61);
            this.SyncHighlightImageButton.TabIndex = 20;
            this.SyncHighlightImageButton.UseVisualStyleBackColor = false;
            this.SyncHighlightImageButton.Visible = false;
            this.SyncHighlightImageButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.SyncHighlightImageButton_MouseDown);
            this.SyncHighlightImageButton.MouseEnter += new System.EventHandler(this.SyncHighlightImageButton_MouseEnter);
            this.SyncHighlightImageButton.MouseLeave += new System.EventHandler(this.SyncHighlightImageButton_MouseLeave);
            this.SyncHighlightImageButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.SyncHighlightImageButton_MouseUp);
            // 
            // HighlightModeLabel
            // 
            this.HighlightModeLabel.AutoSize = true;
            this.HighlightModeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.HighlightModeLabel.Location = new System.Drawing.Point(484, 18);
            this.HighlightModeLabel.Name = "HighlightModeLabel";
            this.HighlightModeLabel.Size = new System.Drawing.Size(176, 29);
            this.HighlightModeLabel.TabIndex = 21;
            this.HighlightModeLabel.Text = "Highlight mode";
            this.HighlightModeLabel.Visible = false;
            // 
            // LeftPanel
            // 
            this.LeftPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.LeftPanel.Location = new System.Drawing.Point(45, 95);
            this.LeftPanel.Name = "LeftPanel";
            this.LeftPanel.Size = new System.Drawing.Size(252, 538);
            this.LeftPanel.TabIndex = 22;
            this.LeftPanel.Paint += new System.Windows.Forms.PaintEventHandler(this.LeftPanel_Paint);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(233)))), ((int)(((byte)(242)))));
            this.panel1.Controls.Add(this.RightPanelServiceLabel);
            this.panel1.Controls.Add(this.RightPanelSearchingLabel);
            this.panel1.Controls.Add(this.RightPanelTittleLabel);
            this.panel1.Controls.Add(this.XRightPanelImageButton);
            this.panel1.Controls.Add(this.RightArrowImageButton);
            this.panel1.Controls.Add(this.LeftArrowImageButton);
            this.panel1.Location = new System.Drawing.Point(891, 95);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(369, 538);
            this.panel1.TabIndex = 23;
            // 
            // RightPanelServiceLabel
            // 
            this.RightPanelServiceLabel.AutoSize = true;
            this.RightPanelServiceLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RightPanelServiceLabel.Location = new System.Drawing.Point(108, 508);
            this.RightPanelServiceLabel.Name = "RightPanelServiceLabel";
            this.RightPanelServiceLabel.Size = new System.Drawing.Size(179, 22);
            this.RightPanelServiceLabel.TabIndex = 28;
            this.RightPanelServiceLabel.Text = "Service: <API name>";
            // 
            // RightPanelSearchingLabel
            // 
            this.RightPanelSearchingLabel.AutoSize = true;
            this.RightPanelSearchingLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RightPanelSearchingLabel.Location = new System.Drawing.Point(101, 27);
            this.RightPanelSearchingLabel.Name = "RightPanelSearchingLabel";
            this.RightPanelSearchingLabel.Size = new System.Drawing.Size(186, 22);
            this.RightPanelSearchingLabel.TabIndex = 28;
            this.RightPanelSearchingLabel.Text = "Searching: <Content>";
            // 
            // RightPanelTittleLabel
            // 
            this.RightPanelTittleLabel.AutoSize = true;
            this.RightPanelTittleLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RightPanelTittleLabel.Location = new System.Drawing.Point(174, 5);
            this.RightPanelTittleLabel.Name = "RightPanelTittleLabel";
            this.RightPanelTittleLabel.Size = new System.Drawing.Size(56, 22);
            this.RightPanelTittleLabel.TabIndex = 28;
            this.RightPanelTittleLabel.Text = "Tittle";
            // 
            // HighlightModeImageButton
            // 
            this.HighlightModeImageButton.FlatAppearance.BorderSize = 0;
            this.HighlightModeImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.HighlightModeImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.HighlightModeImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.HighlightModeImageButton.Image = global::AugmentedReadingApp.Properties.Resources.HighlightModeButtonImage;
            this.HighlightModeImageButton.Location = new System.Drawing.Point(575, 518);
            this.HighlightModeImageButton.Name = "HighlightModeImageButton";
            this.HighlightModeImageButton.Size = new System.Drawing.Size(60, 60);
            this.HighlightModeImageButton.TabIndex = 48;
            this.HighlightModeImageButton.UseVisualStyleBackColor = true;
            this.HighlightModeImageButton.Click += new System.EventHandler(this.HighlightModeImageButton_Click);
            this.HighlightModeImageButton.MouseEnter += new System.EventHandler(this.HighlightModeImageButton_MouseEnter);
            this.HighlightModeImageButton.MouseLeave += new System.EventHandler(this.HighlightModeImageButton_MouseLeave);
            // 
            // WebSearcherImageButton
            // 
            this.WebSearcherImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.WebSearcherImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.WebSearcherImageButton.FlatAppearance.BorderSize = 0;
            this.WebSearcherImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.WebSearcherImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.WebSearcherImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.WebSearcherImageButton.Image = global::AugmentedReadingApp.Properties.Resources.WebSearcherButtonOFFImage;
            this.WebSearcherImageButton.Location = new System.Drawing.Point(660, 515);
            this.WebSearcherImageButton.Name = "WebSearcherImageButton";
            this.WebSearcherImageButton.Size = new System.Drawing.Size(81, 65);
            this.WebSearcherImageButton.TabIndex = 47;
            this.WebSearcherImageButton.UseVisualStyleBackColor = false;
            this.WebSearcherImageButton.Click += new System.EventHandler(this.WebSearcherImageButton_Click);
            this.WebSearcherImageButton.MouseEnter += new System.EventHandler(this.WebSearcherImageButton_MouseEnter);
            this.WebSearcherImageButton.MouseLeave += new System.EventHandler(this.WebSearcherImageButton_MouseLeave);
            // 
            // SynchronizerImageButton
            // 
            this.SynchronizerImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.SynchronizerImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.SynchronizerImageButton.FlatAppearance.BorderSize = 0;
            this.SynchronizerImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.SynchronizerImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.SynchronizerImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.SynchronizerImageButton.Image = global::AugmentedReadingApp.Properties.Resources.SynchonizerButtonOFFImage;
            this.SynchronizerImageButton.Location = new System.Drawing.Point(470, 515);
            this.SynchronizerImageButton.Name = "SynchronizerImageButton";
            this.SynchronizerImageButton.Size = new System.Drawing.Size(81, 65);
            this.SynchronizerImageButton.TabIndex = 45;
            this.SynchronizerImageButton.UseVisualStyleBackColor = false;
            this.SynchronizerImageButton.Click += new System.EventHandler(this.SynchronizerImageButton_Click);
            this.SynchronizerImageButton.MouseEnter += new System.EventHandler(this.SynchronizerImageButton_MouseEnter);
            this.SynchronizerImageButton.MouseLeave += new System.EventHandler(this.SynchronizerImageButton_MouseLeave);
            // 
            // XRightPanelImageButton
            // 
            this.XRightPanelImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.XRightPanelImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.XRightPanelImageButton.FlatAppearance.BorderSize = 0;
            this.XRightPanelImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.XRightPanelImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.XRightPanelImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.XRightPanelImageButton.Image = global::AugmentedReadingApp.Properties.Resources.XButtonImage;
            this.XRightPanelImageButton.Location = new System.Drawing.Point(276, 441);
            this.XRightPanelImageButton.Name = "XRightPanelImageButton";
            this.XRightPanelImageButton.Size = new System.Drawing.Size(81, 61);
            this.XRightPanelImageButton.TabIndex = 44;
            this.XRightPanelImageButton.UseVisualStyleBackColor = false;
            this.XRightPanelImageButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.XRightPanelImageButton_MouseDown);
            this.XRightPanelImageButton.MouseEnter += new System.EventHandler(this.XRightPanelImageButton_MouseEnter);
            this.XRightPanelImageButton.MouseLeave += new System.EventHandler(this.XRightPanelImageButton_MouseLeave);
            this.XRightPanelImageButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.XRightPanelImageButton_MouseUp);
            // 
            // RightArrowImageButton
            // 
            this.RightArrowImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.RightArrowImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.RightArrowImageButton.FlatAppearance.BorderSize = 0;
            this.RightArrowImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.RightArrowImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.RightArrowImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.RightArrowImageButton.Image = global::AugmentedReadingApp.Properties.Resources.RightArrowButtonImage;
            this.RightArrowImageButton.Location = new System.Drawing.Point(141, 441);
            this.RightArrowImageButton.Name = "RightArrowImageButton";
            this.RightArrowImageButton.Size = new System.Drawing.Size(81, 61);
            this.RightArrowImageButton.TabIndex = 43;
            this.RightArrowImageButton.UseVisualStyleBackColor = false;
            this.RightArrowImageButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.RightArrowImageButton_MouseDown);
            this.RightArrowImageButton.MouseEnter += new System.EventHandler(this.RightArrowImageButton_MouseEnter);
            this.RightArrowImageButton.MouseLeave += new System.EventHandler(this.RightArrowImageButton_MouseLeave);
            this.RightArrowImageButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.RightArrowImageButton_MouseUp);
            // 
            // LeftArrowImageButton
            // 
            this.LeftArrowImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.LeftArrowImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.LeftArrowImageButton.FlatAppearance.BorderSize = 0;
            this.LeftArrowImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.LeftArrowImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.LeftArrowImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.LeftArrowImageButton.Image = global::AugmentedReadingApp.Properties.Resources.LeftArrowButtonImage;
            this.LeftArrowImageButton.Location = new System.Drawing.Point(38, 441);
            this.LeftArrowImageButton.Name = "LeftArrowImageButton";
            this.LeftArrowImageButton.Size = new System.Drawing.Size(81, 61);
            this.LeftArrowImageButton.TabIndex = 42;
            this.LeftArrowImageButton.UseVisualStyleBackColor = false;
            this.LeftArrowImageButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.LeftArrowImageButton_MouseDown);
            this.LeftArrowImageButton.MouseEnter += new System.EventHandler(this.LeftArrowImageButton_MouseEnter);
            this.LeftArrowImageButton.MouseLeave += new System.EventHandler(this.LeftArrowImageButton_MouseLeave);
            this.LeftArrowImageButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.LeftArrowImageButton_MouseUp);
            // 
            // HistoryImageButton
            // 
            this.HistoryImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.HistoryImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.HistoryImageButton.FlatAppearance.BorderSize = 0;
            this.HistoryImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.HistoryImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.HistoryImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.HistoryImageButton.Image = global::AugmentedReadingApp.Properties.Resources.HistoryButtonImage;
            this.HistoryImageButton.Location = new System.Drawing.Point(93, 15);
            this.HistoryImageButton.Name = "HistoryImageButton";
            this.HistoryImageButton.Size = new System.Drawing.Size(81, 61);
            this.HistoryImageButton.TabIndex = 39;
            this.HistoryImageButton.UseVisualStyleBackColor = false;
            this.HistoryImageButton.Click += new System.EventHandler(this.HistoryImageButton_Click);
            this.HistoryImageButton.MouseEnter += new System.EventHandler(this.HistoryImageButton_MouseEnter);
            this.HistoryImageButton.MouseLeave += new System.EventHandler(this.HistoryImageButton_MouseLeave);
            // 
            // TurnOffImageButton
            // 
            this.TurnOffImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.TurnOffImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.TurnOffImageButton.FlatAppearance.BorderSize = 0;
            this.TurnOffImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.TurnOffImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.TurnOffImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.TurnOffImageButton.Image = global::AugmentedReadingApp.Properties.Resources.TurnOffButtonImage;
            this.TurnOffImageButton.Location = new System.Drawing.Point(1190, 18);
            this.TurnOffImageButton.Name = "TurnOffImageButton";
            this.TurnOffImageButton.Size = new System.Drawing.Size(81, 61);
            this.TurnOffImageButton.TabIndex = 38;
            this.TurnOffImageButton.UseVisualStyleBackColor = false;
            this.TurnOffImageButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.TurnOffImageButton_MouseDown);
            this.TurnOffImageButton.MouseEnter += new System.EventHandler(this.TurnOffImageButton_MouseEnter);
            this.TurnOffImageButton.MouseLeave += new System.EventHandler(this.TurnOffImageButton_MouseLeave);
            this.TurnOffImageButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.TurnOffImageButton_MouseUp);
            // 
            // ContentImageButton
            // 
            this.ContentImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.ContentImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ContentImageButton.FlatAppearance.BorderSize = 0;
            this.ContentImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.ContentImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.ContentImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ContentImageButton.Image = global::AugmentedReadingApp.Properties.Resources.ContentButtonImage;
            this.ContentImageButton.Location = new System.Drawing.Point(673, 610);
            this.ContentImageButton.Name = "ContentImageButton";
            this.ContentImageButton.Size = new System.Drawing.Size(81, 61);
            this.ContentImageButton.TabIndex = 37;
            this.ContentImageButton.UseVisualStyleBackColor = false;
            this.ContentImageButton.Visible = false;
            this.ContentImageButton.Click += new System.EventHandler(this.ContentImageButton_Click);
            this.ContentImageButton.MouseEnter += new System.EventHandler(this.ContentImageButton_MouseEnter);
            this.ContentImageButton.MouseLeave += new System.EventHandler(this.ContentImageButton_MouseLeave);
            // 
            // FiguresImageButton
            // 
            this.FiguresImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.FiguresImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.FiguresImageButton.FlatAppearance.BorderSize = 0;
            this.FiguresImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.FiguresImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.FiguresImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.FiguresImageButton.Image = global::AugmentedReadingApp.Properties.Resources.FiguresButtonnImage;
            this.FiguresImageButton.Location = new System.Drawing.Point(587, 610);
            this.FiguresImageButton.Name = "FiguresImageButton";
            this.FiguresImageButton.Size = new System.Drawing.Size(81, 61);
            this.FiguresImageButton.TabIndex = 36;
            this.FiguresImageButton.UseVisualStyleBackColor = false;
            this.FiguresImageButton.Visible = false;
            this.FiguresImageButton.Click += new System.EventHandler(this.FiguresImageButton_Click);
            this.FiguresImageButton.MouseEnter += new System.EventHandler(this.FiguresImageButton_MouseEnter);
            this.FiguresImageButton.MouseLeave += new System.EventHandler(this.FiguresImageButton_MouseLeave);
            // 
            // CommentsImageButton
            // 
            this.CommentsImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.CommentsImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.CommentsImageButton.FlatAppearance.BorderSize = 0;
            this.CommentsImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.CommentsImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.CommentsImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.CommentsImageButton.Image = global::AugmentedReadingApp.Properties.Resources.CommentsButtonImage;
            this.CommentsImageButton.Location = new System.Drawing.Point(501, 610);
            this.CommentsImageButton.Name = "CommentsImageButton";
            this.CommentsImageButton.Size = new System.Drawing.Size(81, 61);
            this.CommentsImageButton.TabIndex = 35;
            this.CommentsImageButton.UseVisualStyleBackColor = false;
            this.CommentsImageButton.Visible = false;
            this.CommentsImageButton.Click += new System.EventHandler(this.CommentsImageButton_Click);
            this.CommentsImageButton.MouseEnter += new System.EventHandler(this.CommentsImageButton_MouseEnter);
            this.CommentsImageButton.MouseLeave += new System.EventHandler(this.CommentsImageButton_MouseLeave);
            // 
            // BookmarkImageButton
            // 
            this.BookmarkImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.BookmarkImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BookmarkImageButton.FlatAppearance.BorderSize = 0;
            this.BookmarkImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.BookmarkImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.BookmarkImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.BookmarkImageButton.Image = global::AugmentedReadingApp.Properties.Resources.BookmarkButtonImage;
            this.BookmarkImageButton.Location = new System.Drawing.Point(415, 610);
            this.BookmarkImageButton.Name = "BookmarkImageButton";
            this.BookmarkImageButton.Size = new System.Drawing.Size(81, 61);
            this.BookmarkImageButton.TabIndex = 34;
            this.BookmarkImageButton.UseVisualStyleBackColor = false;
            this.BookmarkImageButton.Visible = false;
            this.BookmarkImageButton.Click += new System.EventHandler(this.BookmarkImageButton_Click);
            this.BookmarkImageButton.MouseEnter += new System.EventHandler(this.BookmarkImageButton_MouseEnter);
            this.BookmarkImageButton.MouseLeave += new System.EventHandler(this.BookmarkImageButton_MouseLeave);
            // 
            // VideosImageButton
            // 
            this.VideosImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.VideosImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.VideosImageButton.FlatAppearance.BorderSize = 0;
            this.VideosImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.VideosImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.VideosImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.VideosImageButton.Image = global::AugmentedReadingApp.Properties.Resources.VideoButtonImage;
            this.VideosImageButton.Location = new System.Drawing.Point(717, 603);
            this.VideosImageButton.Name = "VideosImageButton";
            this.VideosImageButton.Size = new System.Drawing.Size(81, 61);
            this.VideosImageButton.TabIndex = 33;
            this.VideosImageButton.UseVisualStyleBackColor = false;
            this.VideosImageButton.Visible = false;
            this.VideosImageButton.Click += new System.EventHandler(this.VideosImageButton_Click);
            this.VideosImageButton.MouseEnter += new System.EventHandler(this.VideosImageButton_MouseEnter);
            this.VideosImageButton.MouseLeave += new System.EventHandler(this.VideosImageButton_MouseLeave);
            // 
            // ImagesImageButton
            // 
            this.ImagesImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.ImagesImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ImagesImageButton.FlatAppearance.BorderSize = 0;
            this.ImagesImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.ImagesImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.ImagesImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ImagesImageButton.Image = global::AugmentedReadingApp.Properties.Resources.ImagesButtonImage;
            this.ImagesImageButton.Location = new System.Drawing.Point(631, 603);
            this.ImagesImageButton.Name = "ImagesImageButton";
            this.ImagesImageButton.Size = new System.Drawing.Size(81, 61);
            this.ImagesImageButton.TabIndex = 32;
            this.ImagesImageButton.UseVisualStyleBackColor = false;
            this.ImagesImageButton.Visible = false;
            this.ImagesImageButton.Click += new System.EventHandler(this.ImagesImageButton_Click);
            this.ImagesImageButton.MouseEnter += new System.EventHandler(this.ImagesImageButton_MouseEnter);
            this.ImagesImageButton.MouseLeave += new System.EventHandler(this.ImagesImageButton_MouseLeave);
            // 
            // TranslatorImageButton
            // 
            this.TranslatorImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.TranslatorImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.TranslatorImageButton.FlatAppearance.BorderSize = 0;
            this.TranslatorImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.TranslatorImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.TranslatorImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.TranslatorImageButton.Image = global::AugmentedReadingApp.Properties.Resources.TraductorButtonImage;
            this.TranslatorImageButton.Location = new System.Drawing.Point(545, 603);
            this.TranslatorImageButton.Name = "TranslatorImageButton";
            this.TranslatorImageButton.Size = new System.Drawing.Size(81, 61);
            this.TranslatorImageButton.TabIndex = 31;
            this.TranslatorImageButton.UseVisualStyleBackColor = false;
            this.TranslatorImageButton.Visible = false;
            this.TranslatorImageButton.Click += new System.EventHandler(this.TranslatorImageButton_Click);
            this.TranslatorImageButton.MouseEnter += new System.EventHandler(this.TranslatorImageButton_MouseEnter);
            this.TranslatorImageButton.MouseLeave += new System.EventHandler(this.TranslatorImageButton_MouseLeave);
            // 
            // DictionaryImageButton
            // 
            this.DictionaryImageButton.FlatAppearance.BorderSize = 0;
            this.DictionaryImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.DictionaryImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.DictionaryImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DictionaryImageButton.Image = global::AugmentedReadingApp.Properties.Resources.DiccionarioButtonImage;
            this.DictionaryImageButton.Location = new System.Drawing.Point(373, 603);
            this.DictionaryImageButton.Name = "DictionaryImageButton";
            this.DictionaryImageButton.Size = new System.Drawing.Size(81, 61);
            this.DictionaryImageButton.TabIndex = 30;
            this.DictionaryImageButton.UseVisualStyleBackColor = true;
            this.DictionaryImageButton.Visible = false;
            this.DictionaryImageButton.Click += new System.EventHandler(this.DictionaryImageButton_Click);
            this.DictionaryImageButton.MouseEnter += new System.EventHandler(this.DictionaryImageButton_MouseEnter);
            this.DictionaryImageButton.MouseLeave += new System.EventHandler(this.DictionaryImageButton_MouseLeave);
            // 
            // EncyclopediaImageButton
            // 
            this.EncyclopediaImageButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.EncyclopediaImageButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.EncyclopediaImageButton.FlatAppearance.BorderSize = 0;
            this.EncyclopediaImageButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.EncyclopediaImageButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.EncyclopediaImageButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.EncyclopediaImageButton.Image = global::AugmentedReadingApp.Properties.Resources.EncyclopediaButtonImage;
            this.EncyclopediaImageButton.Location = new System.Drawing.Point(459, 603);
            this.EncyclopediaImageButton.Name = "EncyclopediaImageButton";
            this.EncyclopediaImageButton.Size = new System.Drawing.Size(81, 61);
            this.EncyclopediaImageButton.TabIndex = 29;
            this.EncyclopediaImageButton.UseVisualStyleBackColor = false;
            this.EncyclopediaImageButton.Visible = false;
            this.EncyclopediaImageButton.Click += new System.EventHandler(this.EncyclopediaImageButton_Click);
            this.EncyclopediaImageButton.MouseEnter += new System.EventHandler(this.EncyclopediaImageButton_MouseEnter);
            this.EncyclopediaImageButton.MouseLeave += new System.EventHandler(this.EncyclopediaImageButton_MouseLeave);
            // 
            // ProjectionScreen
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(245)))), ((int)(((byte)(250)))));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.ClientSize = new System.Drawing.Size(1280, 720);
            this.Controls.Add(this.HighlightModeImageButton);
            this.Controls.Add(this.WebSearcherImageButton);
            this.Controls.Add(this.SynchronizerImageButton);
            this.Controls.Add(this.HistoryImageButton);
            this.Controls.Add(this.TurnOffImageButton);
            this.Controls.Add(this.ContentImageButton);
            this.Controls.Add(this.FiguresImageButton);
            this.Controls.Add(this.CommentsImageButton);
            this.Controls.Add(this.BookmarkImageButton);
            this.Controls.Add(this.VideosImageButton);
            this.Controls.Add(this.ImagesImageButton);
            this.Controls.Add(this.TranslatorImageButton);
            this.Controls.Add(this.DictionaryImageButton);
            this.Controls.Add(this.EncyclopediaImageButton);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.LeftPanel);
            this.Controls.Add(this.SyncHighlightImageButton);
            this.Controls.Add(this.HighlightModeLabel);
            this.Controls.Add(this.ModeLabel);
            this.Controls.Add(this.CapturedContentPanel);
            this.Controls.Add(this.CapturedContentLabel);
            this.Controls.Add(this.HideCalibrationMarksButton);
            this.Controls.Add(this.SettingsButton);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "ProjectionScreen";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.ProjectionScreen_Load);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.ProjectionScreen_MouseMove);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Button SettingsButton;
        private System.Windows.Forms.Button HideCalibrationMarksButton;
        private System.Windows.Forms.Label CapturedContentLabel;
        private System.Windows.Forms.Panel CapturedContentPanel;
        private System.Windows.Forms.Label ModeLabel;
        private System.Windows.Forms.Button SyncHighlightImageButton;
        private System.Windows.Forms.Label HighlightModeLabel;
        private System.Windows.Forms.Panel LeftPanel;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label RightPanelServiceLabel;
        private System.Windows.Forms.Label RightPanelSearchingLabel;
        private System.Windows.Forms.Label RightPanelTittleLabel;
        private System.Windows.Forms.Button EncyclopediaImageButton;
        private System.Windows.Forms.Button DictionaryImageButton;
        private System.Windows.Forms.Button TranslatorImageButton;
        private System.Windows.Forms.Button ImagesImageButton;
        private System.Windows.Forms.Button VideosImageButton;
        private System.Windows.Forms.Button BookmarkImageButton;
        private System.Windows.Forms.Button CommentsImageButton;
        private System.Windows.Forms.Button FiguresImageButton;
        private System.Windows.Forms.Button ContentImageButton;
        private System.Windows.Forms.Button TurnOffImageButton;
        private System.Windows.Forms.Button HistoryImageButton;
        private System.Windows.Forms.Button LeftArrowImageButton;
        private System.Windows.Forms.Button RightArrowImageButton;
        private System.Windows.Forms.Button XRightPanelImageButton;
        private System.Windows.Forms.Button SynchronizerImageButton;
        private System.Windows.Forms.Button WebSearcherImageButton;
        private System.Windows.Forms.Button HighlightModeImageButton;
        //
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        //[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        //internal ProjectionScreen()
        //{
        //} ESTE CÓDIGO SE GENERÓ SOLO AL IMPORTAR projectionScreen.cs

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AugmentedReadingApp.ProjectionScreen", typeof(ProjectionScreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookmarkButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("BookmarkButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookmarkButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("BookmarkButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookmarkButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("BookmarkButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaptureModeButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("CaptureModeButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaptureModeButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("CaptureModeButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommentsButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("CommentsButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommentsButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("CommentsButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommentsButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("CommentsButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContentButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("ContentButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContentButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("ContentButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContentButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("ContentButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBookmarksButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("DeleteBookmarksButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBookmarksButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("DeleteBookmarksButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBookmarksButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("DeleteBookmarksButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiccionarioButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("DiccionarioButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiccionarioButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("DiccionarioButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiccionarioButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("DiccionarioButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EncyclopediaButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("EncyclopediaButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EncyclopediaButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("EncyclopediaButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EncyclopediaButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("EncyclopediaButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FiguresButtonnClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("FiguresButtonnClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FiguresButtonnHover
        {
            get
            {
                object obj = ResourceManager.GetObject("FiguresButtonnHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FiguresButtonnImage
        {
            get
            {
                object obj = ResourceManager.GetObject("FiguresButtonnImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HighlightModeButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("HighlightModeButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HighlightModeButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("HighlightModeButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HistoryButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("HistoryButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HistoryButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("HistoryButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HistoryButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("HistoryButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagesButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("ImagesButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagesButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("ImagesButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagesButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("ImagesButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrowButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("LeftArrowButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrowButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("LeftArrowButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrowButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("LeftArrowButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("ReadButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("ReadButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("ReadButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrowButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("RightArrowButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrowButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("RightArrowButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrowButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("RightArrowButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SyncHighlightsButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("SyncHighlightsButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SyncHighlightsButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("SyncHighlightsButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SyncHighlightsButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("SyncHighlightsButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SynchonizerButtonOFFImage
        {
            get
            {
                object obj = ResourceManager.GetObject("SynchonizerButtonOFFImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SynchronizerButtonOFFHover
        {
            get
            {
                object obj = ResourceManager.GetObject("SynchronizerButtonOFFHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SynchronizerButtonONHover
        {
            get
            {
                object obj = ResourceManager.GetObject("SynchronizerButtonONHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SynchronizerButtonONImage
        {
            get
            {
                object obj = ResourceManager.GetObject("SynchronizerButtonONImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TraductorButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("TraductorButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TraductorButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("TraductorButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TraductorButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("TraductorButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurnOffButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("TurnOffButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurnOffButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("TurnOffButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurnOffButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("TurnOffButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoButtonClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("VideoButtonClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoButtonHover
        {
            get
            {
                object obj = ResourceManager.GetObject("VideoButtonHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("VideoButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebSearcherButtonOFFHover
        {
            get
            {
                object obj = ResourceManager.GetObject("WebSearcherButtonOFFHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebSearcherButtonOFFImage
        {
            get
            {
                object obj = ResourceManager.GetObject("WebSearcherButtonOFFImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebSearcherButtonOMHover
        {
            get
            {
                object obj = ResourceManager.GetObject("WebSearcherButtonOMHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebSearcherButtonONImage
        {
            get
            {
                object obj = ResourceManager.GetObject("WebSearcherButtonONImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XButtonImage
        {
            get
            {
                object obj = ResourceManager.GetObject("XButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XButtonImageClicked
        {
            get
            {
                object obj = ResourceManager.GetObject("XButtonImageClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XButtonImageHover
        {
            get
            {
                object obj = ResourceManager.GetObject("XButtonImageHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
